#!/bin/bash

# branches not allowed to push
readonly MASTER='master'
# contain release
readonly RELEASE='^.*release.*$'
readonly MAIN='main'

while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ "${remote_ref##refs/heads/}" = $MASTER ]]; then
    echo -e "\033[0;32mDo not push to\033[m\033[1;34m master\033[m \033[0;32mbranch\033[m"
    exit 1
  fi
  if [[ "${remote_ref##refs/heads/}" =~ $RELEASE ]]; then
    echo -e "\033[0;32mDo not push to\033[m\033[1;34m release\033[m \033[0;32mbranch\033[m"
    exit 1
  fi
  if [[ "${remote_ref##refs/heads/}" = $MAIN ]]; then
    echo -e "\033[0;32mDo not push to\033[m\033[1;34m main\033[m \033[0;32mbranch\033[m"
    exit 1
  fi
done
